language: cpp

addons:
  sonarcloud:
    organization: "gautierbureau-github"
    token:
      secure: ${SONAR_TOKEN}

notifications:
  email:
    recipients:
      - gautier.bureau@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

install:
  # We checkout the right commit to test (either a push or a merge test during a pull request)
  # We could also either checkout TRAVIS_BRANCH for the push
  # or use git fetch origin +refs/pull/PR_NUMBER/merge and git checkout FETCH_HEAD for the merge test of a pull request
  - ./install.sh

jobs:
  include:
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Release CXX11_ENABLED=NO COMPILER=GCC LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Release CXX11_ENABLED=YES COMPILER=GCC LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Debug CXX11_ENABLED=NO COMPILER=GCC LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Debug CXX11_ENABLED=YES COMPILER=GCC LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Release CXX11_ENABLED=NO COMPILER=GCC LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Release CXX11_ENABLED=YES COMPILER=GCC LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Debug CXX11_ENABLED=NO COMPILER=GCC LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Debug CXX11_ENABLED=YES COMPILER=GCC LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Release CXX11_ENABLED=NO COMPILER=CLANG LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Release CXX11_ENABLED=YES COMPILER=CLANG LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Debug CXX11_ENABLED=NO COMPILER=CLANG LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env: BUILD_TYPE=Debug CXX11_ENABLED=YES COMPILER=CLANG LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Release CXX11_ENABLED=NO COMPILER=CLANG LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Release CXX11_ENABLED=YES COMPILER=CLANG LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Debug CXX11_ENABLED=NO COMPILER=CLANG LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      compiler: clang++
      env: BUILD_TYPE=Debug CXX11_ENABLED=YES COMPILER=CLANG LIBRARY_TYPE=STATIC
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success"
    - stage: build
      os: osx
      osx_image: xcode10.3
      compiler: clang++
      env: BUILD_TYPE=Release CXX11_ENABLED=YES COMPILER=CLANG LIBRARY_TYPE=SHARED
      script:
        - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        - cd test-travis;./compile.sh build
      after_success:
        - echo "success macos"
